MODULES+=	echo

MODULE_SUMMARY_echo=	3rd-party echo dynamic module

MODULE_CONTRIB_DEPS_echo=	echo-nginx-module

include $(foreach dep,$(MODULE_CONTRIB_DEPS_echo),$(CONTRIB)/src/$(dep)/version)

MODULE_VERSION_echo=	$(ECHO_NGINX_MODULE_VERSION)
MODULE_RELEASE_echo=	1

MODULE_VERSION_PREFIX_echo=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_echo=	echo-nginx-module-$(ECHO_NGINX_MODULE_VERSION).tar.gz

MODULE_CONFARGS_echo=	--add-dynamic-module=echo-nginx-module-$(ECHO_NGINX_MODULE_VERSION)

define MODULE_POST_echo
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_echo) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_http_echo_module.so;

Please refer to the module documentation for further details:
https://github.com/openresty/echo-nginx-module

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_echo
